# pytorch_lightning==1.8.3.post1
seed_everything: 42
trainer:
  logger: false
  enable_checkpointing: false
  callbacks:
  - class_path: callbacks.callbacks.KeyboardCallback
  accelerator: gpu
  devices: 1
  overfit_batches: 1
  max_epochs: -1
  limit_train_batches: null
  limit_val_batches: null
  enable_model_summary: true
  num_sanity_val_steps: 0
model:
  class_path: models.resnet34.ResNet34
  init_args:
    loss_fn: torch.nn.functional.binary_cross_entropy
    # Inception_V3 uses torch.nn.functional.cross_entropy
    # modified_vgg16 uses torch.nn.functional.binary_cross_entropy
    num_classes: 2
    print_metrics: True
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
# lr_scheduler:
#   class_path: torch.optim.lr_scheduler.ExponentialLR
#   init_args:
#     gamma: 0.1
data:
  class_path: dataModules.MfdDataModule.MfdDataModule
  init_args:
    data_dir: data/364/
    batch_size: 10
    num_workers: 0
    train_percent: 0.75
    train_transforms:
      - class_path: torchvision.transforms.ToTensor
        init_args:
      - class_path: torchvision.transforms.Resize
        init_args:
          size: [128, 128]
          # Inception_V3 needs an input shape of [batch_size, 3, 299, 299]
          # modified_vgg16 needs an input shape of [batch_size, 3, 128, 128]
      - class_path: torchvision.transforms.RandomHorizontalFlip
        init_args:
      - class_path: torchvision.transforms.RandomVerticalFlip
        init_args:
      - class_path: torchvision.transforms.Normalize
        init_args:
          mean: [0.1553]
          std: [0.1838]
    val_transforms:
      - class_path: torchvision.transforms.ToTensor
        init_args:
      - class_path: torchvision.transforms.Resize
        init_args:
          size: [224, 224]
      - class_path: torchvision.transforms.Normalize
        init_args:
          mean: [0.1553]
          std: [0.1838]
