# pytorch_lightning==1.8.3.post1
seed_everything: 42
trainer:
  enable_checkpointing: false
  callbacks:
  - class_path: callbacks.callbacks.KeyboardCallback
  accelerator: gpu
  devices: 1
  fast_dev_run: true
  enable_model_summary: true
  num_sanity_val_steps: 1
  log_every_n_steps: 1
model:
  class_path: models.meta_classifier.MetaClassifier
  init_args:
    loss_fn: torch.nn.functional.cross_entropy
    # Inception_V3 uses torch.nn.functional.cross_entropy
    # modified_vgg16 uses torch.nn.functional.binary_cross_entropy
    num_classes: 2
    print_metrics: False
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
# lr_scheduler:
#   class_path: torch.optim.lr_scheduler.ExponentialLR
#   init_args:
#     gamma: 0.1
data:
  class_path: dataModules.MfdDataModule.MfdDataModule
  init_args:
    data_dir: data/364/
    batch_size: 5
    num_workers: 0
    train_percent: 0.6
    balanced: True
    train_transforms:
      - class_path: torchvision.transforms.ToTensor
        init_args:
      # - class_path: torchvision.transforms.Resize
      #   init_args:
      #     size: [299, 299] 
      #     # Inception_V3 needs an input shape of [batch_size, 3, 299, 299]
      #     # modified_vgg16 needs an input shape of [batch_size, 3, 128, 128]
      - class_path: torchvision.transforms.RandomHorizontalFlip
        init_args:
      - class_path: torchvision.transforms.RandomVerticalFlip
        init_args:
      - class_path: torchvision.transforms.Normalize
        init_args:
          mean: [0.1553]
          std: [0.1838]
    val_transforms:
      - class_path: torchvision.transforms.ToTensor
        init_args:
      # - class_path: torchvision.transforms.Resize
      #   init_args:
      #     size: [299, 299]
      - class_path: torchvision.transforms.Normalize
        init_args:
          mean: [0.1553]
          std: [0.1838]
